{{- if .Values.vi2.iframe1.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    ext.lxc.liferay.com/mainDomain: liferaysampleiframe1.lfr.dev
    ext.lxc.liferay.com/domains: liferaysampleiframe1.lfr.dev
  labels:
    lxc.liferay.com/metadataType: ext-provision
    dxp.lxc.liferay.com/virtualInstanceId: vi2.{{ .Values.domainBase }}
    ext.lxc.liferay.com/projectUid: liferaysampleiframe1-projectuid-vi2
    ext.lxc.liferay.com/projectId: liferaysampleiframe1-projectid-vi2
    ext.lxc.liferay.com/serviceUid: liferaysampleiframe1-serviceuid-vi2
    ext.lxc.liferay.com/serviceId: liferaysampleiframe1-serviceid-vi2
  name: liferaysampleiframe1-vi2.{{ .Values.domainBase }}-lxc-ext-provision-metadata
data:
  liferay-sample-iframe-1.client-extension-config.json: |
    {
      "com.liferay.client.extension.type.configuration.CETConfiguration~liferay-sample-iframe-1-counter-app" : {
        ":configurator:policy" : "force",
        "baseURL" : "${portalURL}/o/liferay-sample-iframe-1",
        "buildTimestamp" : {{ now.Unix }},
        "description" : "",
        "dxp.lxc.liferay.com.virtualInstanceId" : "default",
        "name" : "Counter App",
        "projectId" : "liferaysampleiframe1",
        "projectName" : "liferay-sample-iframe-1",
        "properties" : [ ],
        "sourceCodeURL" : "",
        "type" : "iframe",
        "typeSettings" : [ "portletCategoryName=category.client-extensions", "url=https://arnab-datta.github.io/counter-app" ],
        "webContextPath" : "/liferay-sample-iframe-1"
      }
    }
{{- end -}}