{{- if .Values.vi2.instancesettings.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    ext.lxc.liferay.com/mainDomain: liferaysampleinstancesettings.lfr.dev
    ext.lxc.liferay.com/domains: liferaysampleinstancesettings.lfr.dev
  labels:
    lxc.liferay.com/metadataType: ext-provision
    dxp.lxc.liferay.com/virtualInstanceId: vi2.{{ .Values.domainBase }}
    ext.lxc.liferay.com/projectUid: liferaysampleinstancesettings-projectuid-vi2
    ext.lxc.liferay.com/projectId: liferaysampleinstancesettings-projectid-vi2
    ext.lxc.liferay.com/serviceUid: liferaysampleinstancesettings-serviceuid-vi2
    ext.lxc.liferay.com/serviceId: liferaysampleinstancesettings-serviceid-vi2
  name: liferaysampleinstancesettings-vi2.{{ .Values.domainBase }}-lxc-ext-provision-metadata
data:
  liferay-sample-instance-settings-d2q5j1.client-extension-config.json: |
    {
      "com.liferay.portal.security.content.security.policy.internal.configuration.ContentSecurityPolicyConfiguration.scoped~liferay-sample-instance-settings-d2q5j1" : {
        ":configurator:policy" : "force",
        "baseURL" : "${portalURL}/o/liferay-sample-instance-settings",
        "buildTimestamp" : {{ now.Unix }},
        "description" : "",
        "dxp.lxc.liferay.com.virtualInstanceId" : "default",
        "enabled" : true,
        "name" : "Liferay Sample Instance Settings D2Q5J1",
        "policy" : "frame-src http://other.foo;",
        "projectId" : "liferaysampleinstancesettings",
        "projectName" : "liferay-sample-instance-settings",
        "properties" : [ ],
        "sourceCodeURL" : "",
        "type" : "instanceSettings",
        "typeSettings" : [ "enabled=true", "policy=frame-src http://other.foo;" ],
        "webContextPath" : "/liferay-sample-instance-settings"
      }
    }
{{- end -}}