{{- if .Values.v3_liferaycloud_dev.batch.workload.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: v3-liferaycloud-dev-batch
spec:
  backoffLimit: 3
  parallelism: 1
  template:
    spec:
      hostAliases:
      - ip: "10.43.51.23"
        hostnames:
        - "v3.liferaycloud.dev"
      containers:
      - env:
        - name: LIFERAY_BATCH_OAUTH_APP_ERC
          value: liferay-sample-batch-oauth-application-headless-server
        - name: LIFERAY_ROUTES_CLIENT_EXTENSION
          value: /etc/liferay/lxc/ext-init-metadata
        - name: LIFERAY_ROUTES_DXP
          value: /etc/liferay/lxc/dxp-metadata
        image: registry:5000/liferay-sample-batch:latest
        imagePullPolicy: IfNotPresent
        name: liferaysamplebatch
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 41m
            memory: 225Mi
        volumeMounts:
        - mountPath: /etc/liferay/lxc/dxp-metadata
          name: lxc-dxp-metadata
          readOnly: true
        - mountPath: /etc/liferay/lxc/ext-init-metadata
          name: lxc-ext-init-metadata
          readOnly: true
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: v3.liferaycloud.dev-lxc-dxp-metadata
        name: lxc-dxp-metadata
      - configMap:
          defaultMode: 420
          name: liferaysamplebatchserviceid-v3.liferaycloud.dev-lxc-ext-init-metadata
        name: lxc-ext-init-metadata
{{- end -}}