{{- if .Values.v3_liferaycloud_dev.batch.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    ext.lxc.liferay.com/mainDomain: liferaysamplebatch.lfr.dev
    ext.lxc.liferay.com/domains: liferaysamplebatch.lfr.dev
  labels:
    lxc.liferay.com/metadataType: ext-provision
    dxp.lxc.liferay.com/virtualInstanceId: v3.liferaycloud.dev
    ext.lxc.liferay.com/projectUid: liferaysamplebatchprojectuid
    ext.lxc.liferay.com/projectId: liferaysamplebatchprojectid
    ext.lxc.liferay.com/serviceUid: liferaysamplebatchserviceuid
    ext.lxc.liferay.com/serviceId: liferaysamplebatchserviceid
  name: liferaysamplebatch-v3.liferaycloud.dev-lxc-ext-provision-metadata
data:
  liferay-sample-batch.client-extension-config.json: |
    {
      "com.liferay.oauth2.provider.configuration.OAuth2ProviderApplicationHeadlessServerConfiguration~liferay-sample-batch-oauth-application-headless-server" : {
        ".serviceAddress" : "localhost:8080",
        ".serviceScheme" : "http",
        ":configurator:policy" : "force",
        "baseURL" : "${portalURL}/o/liferay-sample-batch",
        "buildTimestamp" : {{ now.Unix }},
        "description" : "",
        "dxp.lxc.liferay.com.virtualInstanceId" : "default",
        "homePageURL" : "$[conf:.serviceScheme]://$[conf:.serviceAddress]",
        "name" : "Liferay Sample OAuth Application Headless Server",
        "projectId" : "liferaysamplebatch",
        "projectName" : "liferay-sample-batch",
        "properties" : [ ],
        "scopes" : [ "Liferay.Headless.Admin.Workflow.everything", "Liferay.Headless.Batch.Engine.everything", "Liferay.Object.Admin.REST.everything" ],
        "sourceCodeURL" : "",
        "type" : "oAuthApplicationHeadlessServer",
        "typeSettings" : [ ".serviceScheme=http", "scopes=Liferay.Headless.Admin.Workflow.everything\nLiferay.Headless.Batch.Engine.everything\nLiferay.Object.Admin.REST.everything", ".serviceAddress=localhost:8080" ],
        "webContextPath" : "/liferay-sample-batch"
      }
    }
{{- end -}}