apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "vi1.{{ .Values.domainBase }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fullname" . }}
            port:
              number: 80
  - host: "vi2.{{ .Values.domainBase }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fullname" . }}
            port:
              number: 80
  - host: "vi3.{{ .Values.domainBase }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fullname" . }}
            port:
              number: 80