apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: &fullname {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: *fullname
subjects:
  - kind: ServiceAccount
    name: *fullname
