apiVersion: v1
kind: Secret
metadata:
  name: &fullname {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: *fullname
type: kubernetes.io/service-account-token
