apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &fullname {{ include "fullname" . }}
  labels: &labels
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: *fullname
      initContainers:
        - name: pre-populate-dxp-data
          image: {{ .Values.image }}
          command: ["/bin/sh","-c"]
          args: ["[ ! -e /dxp-document_library/README.txt ] && cp -rv /opt/liferay/data/document_library/* /dxp-document_library; exit 0"]
          volumeMounts:
          - mountPath: /dxp-document_library
            name: dxp-data-pvc
      containers:
        - name: liferay
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: *fullname
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: *fullname
                  key: namespace
            - name: KUBERNETES_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: *fullname
                  key: ca.crt
            - name: KUBERNETES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: *fullname
                  key: token
            - name: LIFERAY_JPDA_ENABLED
              value: "true"
              # cluster.link.bind.addr["cluster-link-control"]=localhost
            - name: LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_BIND_PERIOD_ADDR_OPENBRACKET__QUOTE_CLUSTER_MINUS_LINK_MINUS_CONTROL_QUOTE__CLOSEBRACKET_
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug-jvm
              containerPort: 8000
              protocol: TCP
            - name: cluster
              containerPort: 7800
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /c/portal/robots
              port: http
            initialDelaySeconds: 600
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /c/portal/robots
              port: http
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - mountPath: /opt/liferay/data/document_library
              name: dxp-data-pvc
      volumes:
        - name: dxp-data-pvc
          persistentVolumeClaim:
            claimName: dxp-data-pvc
